### ISSUE TITLE
broadcasting a transactions throws InvalidRequestError: Transaction is rejected: tx-txlock-conflict (code 16) 

### ISSUE THREAD

**Issue by dashameter** [dashevo/platform#208]
after using the wallet for about 10txs the error `InvalidRequestError: Transaction is rejected: tx-txlock-conflict (code 16)` shows up and no more transactions can be sent a new wallet must be created to continue using it,  I just created 6 or so wallets that I can no longer use, this is using  sdk 3.21.7 and dashmate/0.21.6-test.2

**Comment by dash-maverick** [comment]
moved it to our backlog, seems like something critical - thanks

**Comment by thephez** [comment]
@dashameter This happens when using a storage adapter to avoid resyncing the whole chain, right? I am seeing this error in that situation as well. It seems to me that in some cases a tx is created and sent but the utxos it uses are not marked as spent in storage. I also see the following related error when trying to send a tx: `InvalidRequestError: Transaction already in chain: transaction already in block chain`. 

From what I can see, it appears that data related to my identity create and topup txs are stored properly. But I also do a regular transaction and it is _not_ being stored. That happens to be the last tx in the sequence of what I'm doing, so it could just be the order of operations and unrelated to the type of tx. Thought I'd mention it anyway.

**Comment by markin-io** [comment]
@dashameter I have the same question - do you actually use a storage adapter for that?
If not, can you please provide a code snippet for the case where you have the actual `tx-txlock-conflict` problem?

**Comment by SamKirby22** [comment]
@dashameter as per triage, please attempt to reproduce. Thanks

**Comment by dashameter** [comment]
retest is inconclusive, instead I'm now getting this error https://github.com/dashevo/platform/issues/245

**Comment by dashameter** [comment]
retest passed, at this moment the autofaucet is working
